version: '2'

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - 2182:2181
  kafka:
    image: wurstmeister/kafka:0.9.0.1
    command: start-kafka.sh
    ports:
      - 9094:9092
    environment:
      - KAFKA_ADVERTISED_HOST_NAME=172.17.0.2
      - KAFKA_CREATE_TOPICS="test_topic:1:1"
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2182
    depends_on:
      - zookeeper
  app:
    build:
      context: .
    links:
      - zookeeper
      - kafka
    depends_on:
      - zookeeper
      - kafka
    volumes:
      - .:/usr/src/app
