language: node_js
node_js:
  - "6"
  - "7"
script:
  - yarn run lint
  - yarn run flow
  - yarn run test
  - yarn run build
branches:
  only:
    - master
    - develop
cache:
  directories:
  - $HOME/.npm